### ISSUE TITLE
code avaliability 

### ISSUE THREAD

**Issue by cwangrun** [jdonnelly36/Deformable-ProtoPNet#1]
A very exciting work, when can the code be avaliable?

**Comment by jdonnelly36** [comment]
Hello! I'm currently cleaning the code up to make it a bit more readable, but it will be posted shortly -- by June 30 at the latest.

**Comment by cwangrun** [comment]
Hi, thank you so much for the timely response, looking forward to seeing the exciting work.

**Comment by jdonnelly36** [comment]
The code is now available!
