### ISSUE TITLE
There is a small error in the derivation of the formula. It has been verified many times that the sim function should be + 1

### ISSUE THREAD

**Issue by Zeno673** [jdonnelly36/Deformable-ProtoPNet#8]
![image](https://github.com/jdonnelly36/Deformable-ProtoPNet/assets/111480273/44ee4725-2539-4aa4-bcaa-6800f882c0aa)

**Comment by jdonnelly36** [comment]
Thank you for pointing out this correction -- I've submitted an update to the arXiv version of the paper. Note that this similarity function is only used for illustrative purposes in the paper, and is not actually implemented in the code, so I am closing this issue as resolved.
